blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/bFJxfftGW6
    about: Get direct support and hang out with us
  - name: Wiki
    url: https://github.com/shadps4-emu/shadPS4/wiki
    about: Information, guides, etc.
