blank_issues_enabled: false
contact_links:
  - name: Support Forums
    url: https://forums.shadps4.net/
    about: For community support and answers
  - name: Discord
    url: https://discord.gg/bFJxfftGW6
    about: Get direct support and hang out with us
